Wi-Fi:
  - wifi
  - WiFi
  - WIFI
  - 无线网
  - 无线网络
  - 无线连接
  - WLAN
  - wlan

蓝牙:
  - Bluetooth
  - bluetooth
  - BT
  - bt
  - 蓝牙设备

Microsoft Office:
  - Office
  - office
  - Office365
  - office365
  - Microsoft 365
  - microsoft365
  - O365
  - o365

Excel:
  - excel
  - EXCEL
  - xls
  - xlsx

Word:
  - word
  - WORD
  - doc
  - docx

Outlook:
  - outlook
  - OUTLOOK

BIOS:
  - bios
  - UEFI
  - uefi

ThinkPad:
  - Think Pad
  - think pad
  - TP
  - tp

Lenovo:
  - 联想电脑
  - lenovo
  - LENOVO

Windows:
  - win10
  - Win10
  - windows10
  - Windows10
  - win11
  - Win11
  - windows11
  - Windows11

Windows 7:
  - win7
  - Win7

Windows XP:
  - windows xp
  - xp
  - XP

打印机:
  - Printer
  - printer
